-- CreateEnum
CREATE TYPE "ProjectType" AS ENUM ('WEB', 'DAPP', 'SMART_CONTRACT', 'MOBILE', 'CLI', 'AI', 'API', 'UI_DESIGN', 'UX_DESIGN', 'GRAPHIC_DESIGN', 'BRANDING', 'PROTOTYPE', 'ILLUSTRATION', 'UI_COMPONENTS', 'VIDEO', 'BLOG', 'PODCAST', 'COURSE', 'EBOOK', 'NEWSLETTER', 'TECHNICAL_WRITING', 'CREATIVE_WRITING', 'DOCUMENTATION', 'COPYWRITING', 'OTHER');

-- AlterTable
ALTER TABLE "Project" ADD COLUMN     "projectType" "ProjectType" NOT NULL DEFAULT 'OTHER';
